name: Comment
on: pull_request
jobs:
  comment-id:
    runs-on: ubuntu-latest
    permissions:
      pull-request: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "hello, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        #깃허브 CLI 인증 토큰