name: Conditions workflow
on: 
  workflow_dispatch:
    inputs:
      level:
        type: choice
        options:
          - info
          - warn
jobs:
  skip-or-run:
    if: ${{ github.actor == 'octocat'}}
    runs-on: ubuntu-latest
    steps:
        - run: echo "Hello"