name: Conditions
on: 
  workflow_dispatch:
    inputs:
      level:
        type: choice
        options:
          - info
          - warn
jobs:
    skip-or-run:
        runs-on: ubuntu-latest
        steps:
            - run: echo 'Hello'
              if: ${{ contains(github.run_id, '1') }}  #워크플로 실행 ID를 기준으로 분기 실행 아이디에 1이 포함되는 경우만 실행