name: Hash Function
on: 
  workflow_dispatch:
    inputs:
      level:
        type: choice
        options:
          - info
          - warn
jobs:
    hash256:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: echo "${HASH}"
            env:
              HASH: ${{ hashFiles('.github/workflows/*.yml') }}    # 해시값 생성