name: Literals
on: # 워크 플로우 이벤트 훅 
  workflow_dispatch:
    inputs:
      greeting:                    # 입력 파라미터명
       type: string                # 데이터형
       default: Hello              # 기보값
       required: true              #파라미터 필수여부
       description: A cheeful word #파라미터 개요s
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAK_'
        env:
          LITERAL_NULL: ${{ null }}        # null형 
          LITERAL_BOOLEAN: ${{ true }}     # boolean형   
          LITERAL_NUMBER: ${{ 1234 }}      # number형  
          LITERAL_STRING: ${{ 'Hello' }}   # string형  (일반)   
          LITERAL_OMIT_STRING: World       # string형  (생략) 