name: Log group
on: # 워크 플로우 이벤트 훅 
  workflow_dispatch:
    inputs:
      greeting:                    # 입력 파라미터명
       type: string                # 데이터형
       default: Hello              # 기보값
       required: true              #파라미터 필수여부
       description: A cheeful word #파라미터 개요
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo "::group::show environment variables"   #로그 그룹화
        printenv
        echo "::debug::This is a debug log"
        echo "::endgroup::"                          #로그 그룹화 종료
