name: Matrix
on: 
  workflow_dispatch:
    inputs:
      level:
        type: choice
        options:
          - info
          - warn
jobs:
  print:
     strategy:
       matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
     runs-on: ${{ matrix.os }}
     steps:
       - run: echo "This is ${RUNNER_OS}"
         shell: bash