name: GITHUB_OUTPUT
on: push
jobs:
    share-data2:
        runs-on: ubuntu-latest
        steps:
            - id: source                                     # 스텝 아이디 설정
              run: echo "result=Hello" >> "${GITHUB_OUTPUT}" # GITHUB_OUTPUT에 기록
            - env:
                RESULT: ${{ steps.source.outputs.result }}   # steps 콘텍스트를 통해 참조
              run: echo "${RESULT}"