name: toJSON
on: 
  workflow_dispatch:
    inputs:
      level:
        type: choice
        options:
          - info
          - warn
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
        - run: echo "${CONTEXT}"
          env:
            CONTEXT: ${{ toJSON(github) }}