name: Missing share data
on:
 workflow_dispatch:
   inputs:
     log-level:
       type: choice
       options:
         - info
         - warn
jobs:
  missing-share:
    runs-on: ubuntu-latest
    steps:
      - run: export RESULT="hello"    #환경변수 임포트
      - run: echo "${RESULT}"         #변수 전달 안됨
  